### ISSUE TITLE
Deparmental Listing

### ISSUE THREAD

**Issue by bds002** [magfest/production-config#134]
So in doing the Department names changes outlined in: 
https://github.com/magfest/production-config/pull/130/files

We created a separate but should be easily fixable issue.

The file name for Concert was changed to Main Theater Tech
The file name for Concert Security was changed to Main Theater Ops:
-  concert: "Concert"
-  concert_security: "Concert Security"
+  concert_ops: "Main Theater Operations" #includes stage hands and concert security
+  concert_tech: "Main Theater Tech"

The problem this created is that we had staff/volunteers already assigned to the concert and concert security, since the names of the departments got changed, new enum's where created.  It might have been easier best to just re-name the displayed name in " " instead creating enum's.

Solving this is either:
- renaming the Concert things back to their old names, 
- or changing the Enum that folks are assigned to.   

I would prefer the 2nd choice and make the following corrections:
- Anyone currently with enum 163373830 (concert dept) would go to 249591743 (Main Theater Operations)
- Anyone currently with enum  37789020 (concert_security) would also go to 249591743 (Main Theater Operations)

The end goal here is that Main Theater Operations is the department that handles where people should be somewhere (Concert Security, stage hands, stage managers etc.. etc..)
Main Theater Tech is those folks handling Equipment (Lights, sounds, video, sound checks etc etc).

**Comment by EliAndrewC** [comment]
I did this last night.
