### ISSUE TITLE
Super MAGFest 2018 preregistration configuration updates

### ISSUE THREAD

**Issue by RobRuana** [magfest/production-config#234]
This is a catch-all issue for configuration changes that need to be made for Super MAGFest 2018 preregistration.

- [x] Dealer registration should OPEN Sunday, July 30th, 12pm Eastern
- [x] Dealer registration should CLOSE by Tuesday, August 1st 11:59am Eastern
- [x] Dealer registration should CAP at 500 applications
- [x] Double check dealer table pricing (get this from @nickthenewbie1)
- [ ] Ensure `prereg_hotel_info_link` is correctly set in the secrets config on `mcp`, see https://github.com/magfest/ubersystem/issues/2576
- [x] Determine max numbers of staff badges that MAGFest can support, see [OFFICE-1170](https://jira.magfest.net/browse/OFFICE-1170) on JIRA
- [x] Double check attendee registration opening dates
- [x] Update badge pricing, price bump counts, and price bump dates (get this from @nickthenewbie1)
- [x] Determine if we should shut off automated emails during preregistration (hopefully don't need to)
- [x] Look at bumping DaemonTask intervals
- [x] Verify super2018 is using the correct stripe keys
- [ ] Determine "sender" and "signature" for hotel booking info email (see `prereg_hotel_info_email_sender` and `prereg_hotel_info_email_signature`)
- [x] Double check the whole config with @binary1230

**Comment by dlenik** [comment]
should this task be used to ensure that attendee registration opening dates are also checked?

**Comment by nickthenewbie1** [comment]
Update dealer reg info.

dealer open : Sun July 30 12pm eastern
Dealer end: Tues Aug 1 11:59am Eastern OR 500 applications

**Comment by RobRuana** [comment]
Overcome by events.
